
INSERT INTO profile_photo (IDPROFILE_PHOTO, TYPE, IMAGE) VALUES (1, NULL, NULL);

INSERT INTO USERS (idusers, name, surname, address, email, admin, password,CITY, ZIP_CODE,PROFILE_PHOTO_IDPROFILE_PHOTO)
VALUES (01, 
"ADMIN",
"ADMIN",
"ADMIN",
"phonemarketintechs2@gmail.com",
1,
"ADMIN",
"Paris",
75015,
1
);

INSERT INTO MARK ( name)
VALUES (
"Apple"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Samsung"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Google"
); 

INSERT INTO MARK (name)
VALUES ( 
"Huawei"
); 

INSERT INTO MARK ( name)
VALUES (
"Xiaomi"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Sony"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Lenovo"
); 

INSERT INTO MARK ( name)
VALUES ( 
"LG"
); 

INSERT INTO MARK ( name)
VALUES ( 
"HTC"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Asus"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Oppo"
); 

INSERT INTO MARK ( name)
VALUES ( 
"One plus"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Wiko"
); 
INSERT INTO MARK ( name)
VALUES ( 
"Motorola"
); 

INSERT INTO MARK ( name)
VALUES ( 
"Blackberry"
); 

INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 4', '8Go,16Go,32Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 5', '16Go,32Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 6', '16Go,32Go,64Go;128Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 6 Plus', '16Go,64Go,128', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 7', '32Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 7 Plus', '8Go,16Go,32Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 8', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 8 Plus', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone XS', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone XR', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 11', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 12', '64Go,128Go,256Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Iphone 12 pro', '128Go,256Go,512Go', '1');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Samsung Galaxy S6 Edge+', '32Go,64Go', '2');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Samsung Galaxy S7', '32Go', '2');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Samsung Galaxy S8', '64Go', '2');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Samsung Galaxy S8+', '64Go,128', '2');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Samsung Galaxy S9', '64Go,', '2');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Pixel 2', '64Go,128Go', '3');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Pixel 3', '64Go', '3');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Pixel 4', '64Go,128Go', '3');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P Smart', '64Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P20 Pro', '64Go,128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P20', '64Go,128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei Y7', '16Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei Y6', '16Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P Smart+', '64Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei Mate 20 Lite', '64Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei Mate 20', '128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei Mate 20 Pro', '128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P30 Pro', '128Go,256Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P40 lite', '128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Huawei P Smart 2021', '128Go', '4');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Poco M3', '64Go,128Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Redmi 9T', '64Go,128Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Redmi Note 9T', '64Go,128Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Mi 11', '128Go,256Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Redmi Note 10 ', '64Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Mi Lite 5G', '128Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Xiaomi Redmi Note 10 5G', '64Go', '5');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XA2 Ultra', '32Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XA2', '32Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia L2', '32Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XZ2', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XZ2 Compact', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XZ2 Premium', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XA2 Plus', '32Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia XZ3', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia 10', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia L3', '32Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia 1', '128Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia 10 Plus', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Sony Xperia L4', '64Go', '6');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo Moto G4', '8Go,16Go', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo Moto G5', '16Go', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo Moto G5s Plus', '32Go', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo K5', '16Go', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo K6', '16Go', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Lenovo P2', '32o', '7');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Optimus L9', '16Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Optimus G', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Optimus G pro', '16Go,32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Optimus F5', '8Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G2', '16,32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G Flex', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G2 Mini', '8Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG F70', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G3', '16Go,32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G3 S', '8Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG F60', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G Flex2', '16Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G4', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Bello 2', '8Go,16Go,32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Nexus 5X', '16Go,32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG K10', '16Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G5', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG K4', '8Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG K8', '6Go,16Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG G6', '32Go,64Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG Q6', '32Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'LG V30', '64Go', '8');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 820', '16Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 620', '8Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC One M9+', '32Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire Eye', '16Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 626', '16Go,32Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC One A9', '16Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC 10', '32Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 530', '16Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC U Ultra', '64Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC U Play', '32Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC 11life', '32Go,64Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC 11+', '128Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Desire 12', '32Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC U12+', '64Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC 12life', '64Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 20 pro', '128Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'HTC Desire 21 pro 5G', '128Go', '9');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 4', '64Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 5', '64Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 6', '128gO,256Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 7 PRO', '256Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 8 Flip', '128Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore 8', '256Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS Zenfore MAX PRO M1', '32Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS ROG Phone', '128Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS ROG Phone 2', '256Go,512Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS ROG Phone 3', '512Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'ASUS ROG Phone 5', '128Go', '10');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X', '256Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo R15 PRO', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo RX17 PRO', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo RX17 NEO', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo RX17 NEO', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A3', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo AX7', '64Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Reno', '256Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Reno Z', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Reno2', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A9', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A5', '64Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X2 Pro', '512Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X2 Neo', '256Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X2 lite', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A72', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A53s', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A15', '32Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X3 Pro 5G', '256Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X3 Neo', '256Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo Find X3lite', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A94 5G', '128Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Oppo A54 5G', '64Go', '11');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus Nord', '128Go,256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus Nord N10', '128Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 8 Pro', '128Go,256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 6T', '128Go,256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 7T', '128Go,256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 7T Pro', '256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 8T', '128Go,256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 9', '256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'OnePlus 9 Pro', '256Go', '12');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View2', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Lenny5', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View2 Pro', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View Max', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Tommy3', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View Go', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View Lite', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Jerry 3', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View2 Plus', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Harry2', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View3', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View3 lite', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View3 Pro', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y60', '128Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y80', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View4', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View4 Lite', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y61', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko View5', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y81', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y51', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko Y62', '16Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko U30', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko U20', '64Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Wiko U10', '32Go', '13');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto g Pro', '128Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto G9 Play', '64Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto e7 plus', '64Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Razr 5G', '256Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto g9 plus', '128Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto G9 Power', '128Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto G 5G', '64Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto E7', '32Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto E7i Power', '32Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto g50', '64Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Motorola Moto g100', '128Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Pearl 8100', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Curve', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Z10', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Q10', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Q5', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Classic', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Leap', '16Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Bold 9700', '0.256Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Motion', '32Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Keyone', '32Go', '14');
INSERT INTO MODEL ( `NAME`, `CAPACITY`, `MARK_IDMARK`) VALUES ( 'Blackberry Torch 9860', '4Go', '14');




