<?php
include_once('Model/ConnectDataBase.php');


function getAllSmartphoneAndroid()
{
    $pdo = connectDB();
    $requete = $pdo->prepare("SELECT MARK.IDMARK, MODEL.NAME, MODEL.IDMODEL, IDSMARTPHONES, TYPE,IMAGE,USERS_IDUSERS, DESCRIPTION,PRICE,STATE,COLOR,SMARTPHONES.CAPACITY,SMARTPHONES.SOLD,PICTURES_IDPICTURES FROM MARK JOIN MODEL ON MODEL.MARK_IDMARK = MARK.IDMARK JOIN SMARTPHONES ON MODEL.IDMODEL = SMARTPHONES.MODEL_IDMODEL JOIN PICTURES ON PICTURES.IDPICTURES  = SMARTPHONES.PICTURES_IDPICTURES
    WHERE SMARTPHONES.SOLD = 0 AND MARK.NAME != 'Apple'");
    $requete->execute();
    $stock = $requete->fetchAll();

    return $stock;
}

function getAllSmartphoneApple()
{
    $pdo = connectDB();
    $requete = $pdo->prepare("SELECT MARK.IDMARK, MODEL.NAME, MODEL.IDMODEL, IDSMARTPHONES, TYPE,IMAGE,USERS_IDUSERS, DESCRIPTION,PRICE,STATE,COLOR,SMARTPHONES.CAPACITY,SMARTPHONES.SOLD,PICTURES_IDPICTURES FROM MARK JOIN MODEL ON MODEL.MARK_IDMARK = MARK.IDMARK JOIN SMARTPHONES ON MODEL.IDMODEL = SMARTPHONES.MODEL_IDMODEL JOIN PICTURES ON PICTURES.IDPICTURES  = SMARTPHONES.PICTURES_IDPICTURES
    WHERE SMARTPHONES.SOLD = 0 AND MARK.NAME = 'Apple'");
    $requete->execute();
    $stock = $requete->fetchAll();

    return $stock;
}

